name: Terraform CI

on: 
	push:
		branches:
			-main
jobs:
	terraform:
		runs-on: ubuntu-latest
		
		steps:
			-name: Checkout code
			uses: actions/checkout@v4

			-name: Setup Terraform
			uses: hashicorp/setup-terraform@v3

			-name: Terraform Init
			uses: terraform init

			-name: Terraform Plan
			uses: terraform plan
